In [1]:
#loc > location, iloc > index location

In [1]:
import numpy as np

In [77]:
demet=('abc', np.arange(0,3,0.2),2.5) #farklı tip veri türlerini içerir

In [78]:
demet

('abc',
 array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
        2.6, 2.8]),
 2.5)

In [4]:
demet [1]

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8])

In [5]:
liste=["a12", "d3f", "ghi4"] #aynı tip verileri içerir

In [6]:
liste.append("21m")

In [7]:
liste

['a12', 'd3f', 'ghi4', '21m']

In [8]:
liste1=["12", "df", "ghi"]

In [9]:
liste+liste1

['a12', 'd3f', 'ghi4', '21m', '12', 'df', 'ghi']

In [10]:
liste2=np.array([1,2,3]) #vektör ve matris formunda veri girişi

In [11]:
liste3=np.array([4,5,6])

In [12]:
liste2+liste3

array([5, 7, 9])

In [13]:
liste2.dot(liste3) #skaler olarak çarpımları

32

In [13]:
#DATA FRAME (VERİ ŞABLONU)
import numpy as np
import pandas as pd

In [14]:
t=np.arange(0,5,0.1) #bunu anlamadım
x=np.sin(t)
y=np.cos(t)
df=pd.DataFrame({"Zaman":t, "sin":x, "cos":y})
df.head(10)

Zaman       sin       cos
0    0.0  0.000000  1.000000
1    0.1  0.099833  0.995004
2    0.2  0.198669  0.980067
3    0.3  0.295520  0.955336
4    0.4  0.389418  0.921061
5    0.5  0.479426  0.877583
6    0.6  0.564642  0.825336
7    0.7  0.644218  0.764842
8    0.8  0.717356  0.696707
9    0.9  0.783327  0.621610

#HOCAYA SOR 

In [15]:
df.sin.head(10)

0    0.000000
1    0.099833
2    0.198669
3    0.295520
4    0.389418
5    0.479426
6    0.564642
7    0.644218
8    0.717356
9    0.783327
Name: sin, dtype: float64

In [16]:
veri=df[["Zaman", "sin"]]
veri.head()

Zaman       sin
0    0.0  0.000000
1    0.1  0.099833
2    0.2  0.198669
3    0.3  0.295520
4    0.4  0.389418

In [17]:
veri[2:5]

Zaman       sin
2    0.2  0.198669
3    0.3  0.295520
4    0.4  0.389418

In [18]:
#series veriler
import pandas as pd
a=[1,3,5,7]
seri=pd.Series(a) #listeyi bir seri haline getirmek için kullanılır.
print(seri)

0    1
1    3
2    5
3    7
dtype: int64


In [19]:
import numpy as np
np.random.seed(seed=0)
x=np.random.randn(6)
y=np.random.randn(5)
z=np.random.randn(3) #HOCAYA SOR

In [20]:
x

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788])

In [21]:
z

array([1.45427351, 0.76103773, 0.12167502])

In [22]:
import pandas as pd

In [23]:
veri2=pd.read_excel("sales_data.xlsx")

In [24]:
veri2

invoice_no customer_id         category  quantity                price  \
0        I138884     C241288         Clothing         5               1500.4   
1        I317333     C111565            Shoes         3              1800.51   
2        I127801     C266599         Clothing         1               300.08   
3        I173702     C988172            Shoes         5              3000.85   
4        I337046     C189076            Books         4                 60.6   
...          ...         ...              ...       ...                  ...   
99452    I219422     C441542         Souvenir         5                58.65   
99453    I325143     C569580  Food & Beverage         2  1946-10-01 00:00:00   
99454    I824010     C103292  Food & Beverage         2  1946-10-01 00:00:00   
99455    I702964     C800631       Technology         4                 4200   
99456    I232867     C273973         Souvenir         3                35.19   

      invoice_date     shopping_mall  
0       2022-08-05            Kanyon  
1       2021-12-12    Forum Istanbul  
2       2021-11-09         Metrocity  
3       2021-05-16      Metropol AVM  
4       2021-10-24            Kanyon  
...            ...               ...  
99452   2022-09-21            Kanyon  
99453   2021-09-22    Forum Istanbul  
99454   2021-03-28         Metrocity  
99455   2021-03-16      Istinye Park  
99456   2022-10-15  Mall of Istanbul  

[99457 rows x 7 columns]

In [25]:
import pandas as pd
veri4=pd.read_excel("veri_analizi_örnek.xlsx")
veri4.head()

FileNotFoundError: [Errno 2] No such file or directory: 'veri_analizi_örnek.xlsx'

In [ ]:
veri4.isnull() #eksik verilerin dosyadan taranması

In [ ]:
veri4.dropna()  #eksik verilerin satırlarını çıkarır

In [ ]:
veri4.fillna(0) #eksik gözlem noktalarını belirtilen değerle doldurur

In [26]:
veri4.bfill()

NameError: name 'veri4' is not defined

In [27]:
veri4.fillna( {"İHRACAT":0.5, "İTHALAT":0}) #değişkenlere göre farklı değer atama

NameError: name 'veri4' is not defined

In [28]:
veri4.fillna({"İHRACAT":0.5, "İTHALAT":0}, inplace=True) #veri setinde değişikliği arka plandada kalıcı hale getirmek

NameError: name 'veri4' is not defined

In [12]:
import pandas as pd
veri4=pd.read_excel("veri_analizi_örnek.xlsx")
veri4.head()

AYLAR   İHRACAT     İTHALAT
0  1998-1   35252.0    235325.0
1  1998-2       NaN  34534534.0
2  1998-3  235545.0         NaN
3  1998-4   42343.0  34534543.0
4  1998-5   76578.0    453576.0

In [13]:
veri4.fillna(method="ffill")

AYLAR   İHRACAT     İTHALAT
0  1998-1   35252.0    235325.0
1  1998-2   35252.0  34534534.0
2  1998-3  235545.0  34534534.0
3  1998-4   42343.0  34534543.0
4  1998-5   76578.0    453576.0

In [14]:
veri4.fillna(method="bfill")

AYLAR   İHRACAT     İTHALAT
0  1998-1   35252.0    235325.0
1  1998-2  235545.0  34534534.0
2  1998-3  235545.0  34534543.0
3  1998-4   42343.0  34534543.0
4  1998-5   76578.0    453576.0

In [21]:
 veri4.fillna(veri4.mean()).head() #eksik gözleme ortalama değeri atar (en mantıklı ve kullanılan yöntem)

NameError: name 'veri4' is not defined

In [9]:
veri4.fillna(veri4.median()).head()#eksik gözleme medyan değeri atar.


NameError: name 'veri4' is not defined

In [16]:
veri4.fillna(veri4.median()).head() #eksik gözleme medyan değeri atar

TypeError: could not convert string to float: '1998-1'

import pandas as pd
veri3=pd.read_excel("örnek2.xlsx")
veri3.head()

In [19]:
import pandas as pd 
veri4=pd.read_excel("örnek2.xlsx") 
veri4.head()

AD CİNSİYET   K1  K2  V1
0    Ali        e  bir   1   0
1   Esra        k  bir   3   2
2  Ahmet        e  iki   1   2
3   Ayşe        k  bir   2   3
4   Emel        k  iki   3   1

In [17]:
veri4.duplicated() #yineleme değerlerinin kontrolünü sağlar

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [ ]:
veri4.drop_duplicated() # yinelemeleri kaldırmak içi kullanılır. Df veri seti olarak tanımlanmalı. 
#Data frame formatında kaydedilmeli

In [20]:
veri5=pd.read_excel("örnek2.xlsx")

In [21]:
veri5

AD CİNSİYET   K1  K2  V1
0      Ali        e  bir   1   0
1     Esra        k  bir   3   2
2    Ahmet        e  iki   1   2
3     Ayşe        k  bir   2   3
4     Emel        k  iki   3   1
5      Can        e  bir   3   4
6  İbrahim        e  bir   4   3
7   Zeynel        e  iki   1   2

In [22]:
veri5.replace("bir", "sekiz")  #değiştirilmesi istenen verileri değiştirmek

AD CİNSİYET     K1  K2  V1
0      Ali        e  sekiz   1   0
1     Esra        k  sekiz   3   2
2    Ahmet        e    iki   1   2
3     Ayşe        k  sekiz   2   3
4     Emel        k    iki   3   1
5      Can        e  sekiz   3   4
6  İbrahim        e  sekiz   4   3
7   Zeynel        e    iki   1   2

In [23]:
veri5.replace("e", "1", inplace=True) 
#inplace=Yanlış silmelerde verinin kalıcı halde silinmesini engeller
veri5.replace("k", "2", inplace=True)
veri5

AD CİNSİYET   K1  K2  V1
0      Ali        1  bir   1   0
1     Esra        2  bir   3   2
2    Ahmet        1  iki   1   2
3     Ayşe        2  bir   2   3
4     Emel        2  iki   3   1
5      Can        1  bir   3   4
6  İbrahim        1  bir   4   3
7   Zeynel        1  iki   1   2

In [56]:
#verideki değişkenlerin isimlerini değiştirmek
veri5.rename(index={"ali":"osman"}, columns={"k1": "sınav"})  

NameError: name 'veri5' is not defined

In [25]:
kukla=pd.get_dummies(veri5["cinsiyet"], prefix="cinsiyet")
kukla
#kategorik değişkene kukla değişkeni atanır

KeyError: 'cinsiyet'

In [26]:
dveri=veri5[["cinsiyet"]].join(kukla)
dveri

KeyError: "None of [Index(['cinsiyet'], dtype='object')] are in the [columns]"

In [27]:
import pandas as pd

In [39]:
df=pd.read_excel("örnek1.xlsx")
df

AYLAR  İHRACAT  İTHALAT
0  1998-1       12       32
1  1998-2       17       34
2  1998-3        9       11
3  1998-4       23       15
4  1998-5       44        6

In [40]:
x=df.İHRACAT
x

0    12
1    17
2     9
3    23
4    44
Name: İHRACAT, dtype: int64

In [41]:
ortalama=sum(x)/len(x) #sum: ifadelerin toplanmış değerini döndürür
ortalama

21.0

In [43]:
import statistics

In [44]:
ortalama=statistics.mean(x)
ortalama

21

In [45]:
import numpy as np

In [ ]:
ortalama=np.nanmean(x) #eksik gözlemi göz ardı ederek ortalama hesabı
ortalama

In [50]:
x=[8,2,2.4,4.2,18]
w=[0.2,0.3,0.4,0.15,0.25]
wmean=sum(w[i]*x[i] for i in range(len(x)))/sum(w)
wmean

6.3769230769230765

In [56]:
import numpy as np

In [52]:
wmean=np.average(x, weights=w)
wmean
#Harmonik ortalama

6.3769230769230765

In [53]:
x=[8,2,2.4,4.2,18]
hort=len(x)/sum(1/item for item in x)
hort

3.744427934621099

In [54]:
import statistics

In [55]:
hort=statistics.harmonic_mean(x)

In [57]:
hort

3.7444279346210996

In [58]:
import scipy.stats

In [59]:
hort=scipy.stats.hmean(x)
hort

3.7444279346210987

# Geometrik Ortalama

In [60]:
gort=1
for item in x:
    gort*=item
gort**=1/len(x)
gort

4.926864336893227

In [61]:
gort=statistics.geometric_mean(x)
gort

4.926864336893226

In [62]:
gort=scipy.stats.gmean(x)
gort

4.926864336893226

# Mod

In [63]:
u= [2,3,2,8,12,5,6,5,2,3] #veride en sık görülen değerdir
u #birden fazla tekrar eden mod varsa (2) buna çoklu mod diyebiliriz

[2, 3, 2, 8, 12, 5, 6, 5, 2, 3]

In [64]:
mod=max((u.count(item), item)for item in set (u))[1]
mod

2

In [66]:
import statistics
mod=statistics.mode(u)
mod

2

In [68]:
u= [2,3,2,8,12,5,6,5,2,3,3] # 3 eklkedik. 3 adet 2 var ve 3 adet 3 var. 
mod=statistics.multimode(u)
mod

[2, 3]

In [69]:
mode=scipy.stats.mode(u)
mode

ModeResult(mode=2, count=3)

In [70]:
veri5.mode()

AD CİNSİYET   K1   K2   V1
0    Ahmet        1  bir  1.0  2.0
1      Ali      NaN  NaN  3.0  NaN
2     Ayşe      NaN  NaN  NaN  NaN
3      Can      NaN  NaN  NaN  NaN
4     Emel      NaN  NaN  NaN  NaN
5     Esra      NaN  NaN  NaN  NaN
6   Zeynel      NaN  NaN  NaN  NaN
7  İbrahim      NaN  NaN  NaN  NaN

In [76]:
x=[2,2,2,2,2,2,2,2,3,3,3,4,4,4,4,4,5,5,5,9,9,9] #medyan küçükten büyüğe sıralarken ortadaki değeri veririr.

In [77]:
n=len(x)
if n % 2:
    medyan=sorted(x)[round(0.5*(n-1))]
else:
    x_ort, index=sorted(x), round(0.5*n)
    medyan=0.5*(x_ord[index-1]+x_ord[index])
medyan

NameError: name 'x_ord' is not defined

In [74]:
import statistics
medyan=statistics.median(x)
medyan

3.5

In [75]:
import numpy as np
medyan=np.median(x)
medyan

3.5

# İKİ BOYUTLU VERİLERDE ÇALIŞMA


In [1]:
import numpy as np
a=np.array([[1,1,1],
            [2,3,1],
            [4,9,1],
            [8,27,4],
            [16,1,1]])        
np.mean(a)

5.333333333333333

In [2]:
np.mean(a, axis=None) #tüm verilerin ortalaması alınır. Axis none ve birin değerini alır. 

5.333333333333333

In [3]:
np.mean(a, axis=0) #axis=0 sütunların ortalamasını alır

array([6.2, 8.2, 1.6])

In [4]:
np.mean(a, axis=1) #axis=1 satırların ortalamasını alır

array([ 1.        ,  2.        ,  4.66666667, 13.        ,  6.        ])

In [5]:
a.var(axis=0, ddof=1) #varyans hesabı

array([ 37.2, 121.2,   1.8])

In [6]:
import numpy as np
import pandas as pd   #veri şablonu oluşturmak için yükledik
a=np.array([[1,1,1],
            [2,3,1],
            [4,9,1],
            [8,27,4],
            [16,1,1]])        

In [7]:
satır_isim=["1","2","3","4","5"]

In [8]:
sütun_isim=["a","b","c"]

In [9]:
df=pd.DataFrame(a, index=satır_isim, columns=sütun_isim)
df

a   b  c
1   1   1  1
2   2   3  1
3   4   9  1
4   8  27  4
5  16   1  1

In [10]:
df.mean()  #her bir sütunun ortalamasını alır

a    6.2
b    8.2
c    1.6
dtype: float64

In [11]:
df.var()  

a     37.2
b    121.2
c      1.8
dtype: float64

In [12]:
df.mean(axis=1) #satırların means fonksiyonuyla 

1     1.000000
2     2.000000
3     4.666667
4    13.000000
5     6.000000
dtype: float64

In [13]:
df.var(axis=1)

1      0.000000
2      1.000000
3     16.333333
4    151.000000
5     75.000000
dtype: float64

In [14]:
df["a"].mean( )#belirli bir satır için hesaplama yapar

6.2

# DEĞİŞKENLİK ÖLÇÜLERİ

VARYANS, STANDART SAPMA, ÇARPIKLIK, BASIKLIK, YÜZDELİKLER, ARALIKLAR

# VARYANS

In [2]:
x=[2,3,2,8,12,5,6,5,2,3] #Varyans kavramı dağılıma ait her bir değerin 
#dağılımın ortalamasından ne kadar uzak olduğuyla ilgilidir.
#Varyans: farkların karesinin ortalamasıdır
#Basitçe söylemek gerekirse, varyans, bir örnek veya veri kümesi içindeki 
#veri noktalarının ne kadar yayılmış olduğunun istatistiksel bir ölçüsüdür.


In [3]:
n=len(x)
n

10

In [4]:
ortalama=sum(x)/n
ortalama

4.8

In [7]:
var=sum((item-ortalama)**2 for item in x)/(n-1)
var

10.4

In [8]:
import numpy as np
var=np.var(x, ddof=1)  
var

10.399999999999999

# STANDART SAPMA (VARYANSIN KAREKÖKÜ)


In [23]:
n=len(x)
mean=sum(x)/n
var=sum((item-mean)**2 for item in x)/(n-1)
stdsapma=var**0.5
stdsapma

3.22490309931942

In [50]:
stdsapma=statistics.stdev(x) #örneklemin standart sapması
stdsapma

3.2249030993194197

In [51]:
stdsapma=statistics.pstdev(x) #popülasyonun standart sapması
stdsapma

3.059411708155671

In [26]:
stdsapma=np.std(x, ddof=1)
stdsapma

3.2249030993194197

In [28]:
çarpıklık=(sum((item-mean)**3 for item in x)*n/((n-1)*(n-2)*stdsapma**3))
çarpıklık

1.367562458291273

In [31]:
import scipy.stats

In [32]:
çarpıklık=scipy.stats.skew(x, bias=False)
çarpıklık

1.3675624582912733

In [33]:
import pandas as pd

In [34]:
x=pd.Series(x)
x.head()

0     2
1     3
2     2
3     8
4    12
dtype: int64

In [35]:
çarpıklık=x.skew()
çarpıklık

1.3675624582912733

# BASIKLIK

In [36]:
basıklık=(((sum((item-mean)**4 for item in x))
        *n/(sum((item-mean)**2 for item in x))**2))-3
basıklık

0.4239535393381546

In [37]:
import scipy.stats

In [38]:
basıklık=scipy.stats.kurtosis(x)
basıklık

0.42395353933815594

In [39]:
df.kurtosis() #pandas ile. Her bir sütunun basıklık değerini hesaplar

a    1.303763
b    3.149691
c    5.000000
dtype: float64

# YÜZDELİKLER

In [40]:
import statistics

In [41]:
statistics.quantiles(x, n=2) #n=2 demek %50 lik kısım demek

[4.0]

In [43]:
statistics.quantiles(x, n=4, method="inclusive")

[2.25, 4.0, 5.75]

In [44]:
import numpy as np

In [45]:
y=np.array(x)
np.percentile(y,10)  #y değişkenin %10 luk kısmının ortalamasını alır

2.0

In [46]:
np.percentile(y,90)

8.399999999999999

In [47]:
import pandas as pd
y=pd.Series(x)
y.quantile(0.10)

2.0

In [48]:
y.quantile(0.90)

8.399999999999999

# TANIMLAYICI İSTATİSTİKLER ÖZETİ

In [49]:
import scipy.stats
scipy.stats.describe(x)

DescribeResult(nobs=10, minmax=(2, 12), mean=4.8, variance=10.4, skewness=1.1532299228638518, kurtosis=0.42395353933815594)

In [57]:
import pandas as pd
sonuc=x.describe()
sonuc

count    10.000000
mean      4.800000
std       3.224903
min       2.000000
25%       2.250000
50%       4.000000
75%       5.750000
max      12.000000
dtype: float64